name: Docs

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        shell: bash
        run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.2 python3 -

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'

      - run: poetry install -E docs

      - run: poetry run mkdocs gh-deploy --force
