name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        shell: bash
        run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.2 python3 -

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}