name: Tests

on: [push]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        shell: bash
        run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.1 python3 -

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Start Ipykernel
        run: poetry run python -m ipykernel_launcher --debug -f /tmp/kernel.json & echo "KERNEL_PID=$!" >> $GITHUB_ENV

      - name: Run tests
        env:
          IPYKERNEL_TEST_CONNECTION_FILE: /tmp/kernel.json
        run: poetry run pytest --reruns 5 -s --log-level DEBUG

      - name: Stop Ipykernel
        if: always()
        run: kill "${{ env.KERNEL_PID }}"
